python train.py \
--train_batch_size 4 \
--num_sample 1 \
--visible_devices "0" \
--num_train_epochs 40 \
--lr 1e-4 \
--obj_cat bunny \
--precision_level median \
--normalization_type group \
--num_groups 16 \
--group develop \
--job median_bunny \
--name 4_blocks_all_median \
--wandb False